#!/bin/sh
# For what ever reason JAVA got corrupted on my machine
# It was causing weird weird errors with eclipse and it's jdt debugger
# I wasn't able to load the JRE's I installed into eclipse
# Eventually after much fiddling this was the only thing that worked.
# I was about to just git up and switch machines / OS's for the night

###########################
#COMPLETELY REMOVE JAVA
#	FROM
#	http://askubuntu.com/questions/84483/how-to-completely-uninstall-java
#########################################################################
	
#Remove all the Java related packages (Sun, Oracle, OpenJDK, IcedTea plugins, GIJ):
	sudo apt-get update
	apt-cache search java | awk '{print($1)}' | grep -E -e '^(ia32-)?(sun|oracle)-java' -e '^openjdk-' -e '^icedtea' -e '^(default|gcj)-j(re|dk)' -e '^gcj-(.*)-j(re|dk)' -e 'java-common' | xargs sudo apt-get -y remove
	sudo apt-get -y autoremove
	
#Purge config files:
	dpkg -l | grep ^rc | awk '{print($2)}' | xargs sudo apt-get -y purge
	
#Remove Java config and cache directory:
	sudo bash -c 'ls -d /home/*/.java' | xargs sudo rm -rf
	
#Remove manually installed JVMs:
	sudo rm -rf /usr/lib/jvm/*
	
#Remove Java entries, if there is still any, from the alternatives:
	for g in ControlPanel java java_vm javaws jcontrol jexec keytool mozilla-javaplugin.so orbd pack200 policytool rmid rmiregistry servertool tnameserv unpack200 xulrunner-1.9-javaplugin.so; do sudo update-alternatives --remove-all $g; done

#Search for possible remaining Java directories:
	sudo updatedb
	sudo locate -b '\pack200'

#################################
# Reinstall JAVA stuff
################################
	sudo apt-get install openjdk-7-jre